[hugo-deployer-git]
    # required
    repo = "https://github.com/ianre657/test-publisg-website.git"
    branch =  "master"

    # optoinal
    name= "haha"
    email= "test@testtest.com"
    message = ""
    build-config= "--minify"